# Generated by Django 2.2 on 2021-04-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saver', '0002_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='spot',
        ),
        migrations.AddField(
            model_name='space',
            name='spot',
            field=models.ManyToManyField(related_name='spot', to='saver.User'),
        ),
    ]
